### ISSUE TITLE
sync_packages: command not found

### ISSUE THREAD

**Issue by ael-code** [archlinuxfr/yaourt#244]
using `yaourt -P` I'm encountering:
```
/usr/lib/yaourt/pkgbuild.sh: line 268: sync_packages: command not found
```

#### installed packages:
 - yaourt 1.8.1-1
 - diffutils 3.3-2
 - pacman 5.0.1-2
 - package-query 1.8-1
 - gettext 0.19.7-1

**Comment by f2404** [comment]
Weird... Is this happening with `yaourt -P` only?

**Comment by larchunix** [comment]
#245 should fix this issue. Could you try it before I merge ?

**Comment by ael-code** [comment]
sorry I cannot recreate the problem.

**Comment by pydsigner** [comment]
I ran into this same problem and can confirm that #245 fixed the problem.

**Comment by ATrigger** [comment]
Ran into the problem today.
Yaourt 1.8.1-1.
/usr/lib/yaourt/pkgbuild.sh: line 268: sync_packages: команда не найдена

**Comment by f2404** [comment]
@ATrigger This is because the issue was fixed after the 1.8.1 had been released. Please try -git version.

**Comment by wget** [comment]
@larchunix 2017: Maybe it would be time to release a new version (e.g.: 1.8.2) to let benefit everyone from this fix. ;-)

**Comment by Enelar** [comment]
@larchunix @f2404 As newbie from Fedora (->Manjaro) just bumped into this issue.
Since https://github.com/archlinuxfr/yaourt/pull/245 is merged, probably we should publish fix?

**Comment by f2404** [comment]
@Enelar Unfortunately, I have no right to make yaourt releases.
But you can still install yaourt-git from AUR.

**Comment by Enelar** [comment]
@f2404 Yep, but the issue still persists for a bunch of newbies like myself.

**Comment by f2404** [comment]
@Skunnyk What about a new release, er?

**Comment by patrickelectric** [comment]
yaourt 1.8.1
problem with `yaourt -P`
