### ISSUE TITLE
Empty 'required by' message when dependency provided by other package

### ISSUE THREAD

**Issue by diffycat** [archlinuxfr/yaourt#39]
E.g. I want to update skype and it has new dependency, `lib32-pulseaudio`:

    ==> Software upgrade (new version) :
    multilib/skype            4.2.0.13-4 -> 4.3.0.37-1

    ==> New package :
    multilib/lib32-json-c     0.12-1     (required by lib32-libpulse)
    multilib/lib32-libasyncns 0.8-6      (required by lib32-libpulse)
    multilib/lib32-libcap     2.24-1     (required by lib32-libpulse)
    multilib/lib32-libxtst    1.2.2-1    (required by lib32-libpulse)
    multilib/lib32-libogg     1.3.1-1    (required by lib32-flac)
    multilib/lib32-flac       1.3.0-1    (required by lib32-libsndfile)
    multilib/lib32-libvorbis  1.3.4-1    (required by lib32-libsndfile)
    multilib/lib32-libsndfile 1.0.25-2   (required by lib32-libpulse)
    multilib/lib32-libpulse   5.0-1      (required by -)

The thing is that repository doesn't contains `lib32-pulseaudio`, but it has `lib32-libpulse` which provides that package.

**Comment by warnaud** [comment]
Got the same issue this morning : 
==> New package :
extra/l-smash                 2.3.0-2          (required by -)


Thanks,

Arnaud

**Comment by larchunix** [comment]
yaourt uses package-query to find reverse dependencies.

    $ package-query -S --qdepends -f %n l-smash

    $ package-query -S --qdepends -f %n liblsmash.so
    x264
    vapoursynth-plugin-lsmashsource

IMHO this issue should be fixed in package-query, not in yaourt.

**Comment by f2404** [comment]
Hi,
I've encountered this issue with ```vid.stab``` today, when updating ```ffmpeg```.
Now, vid.stab is said to be required by ffmpeg; but ffmpeg is not having vid.stab among its dependencies.
How do you think this should be handled by package-query?
```
$ yaourt -Qi vid.stab
Required By    : ffmpeg
```
```
$ yaourt -Qi ffmpeg
Depends On     : alsa-lib  bzip2  fontconfig  fribidi  gnutls  gsm  lame  libass  libbluray  libmodplug  libpulse  libsoxr  libssh  libtheora  libva
                 libvdpau  libwebp  opencore-amr  openjpeg  opus  schroedinger  sdl  speex  v4l-utils  xvidcore  zlib  libvidstab.so=1.1-64
                 libvorbis.so=0-64  libvorbisenc.so=2-64  libvpx.so=2-64  libx264.so=148-64  libx265.so=68-64
```

**Comment by f2404** [comment]
Okay, it looks like ```ffmpeg``` is requiring ```libvidstab.so=1.1-64```, and ```vid.stab``` is providing it.
So, probably package-query should improve handling of the 'provided' items as requirements...
```$ yaourt -Qi vid.stab
Name           : vid.stab
Provides       : libvidstab.so=1.1-64
```

**Comment by f2404** [comment]
Actually, I think this can be resolved in yaourt. Please check my patch.

**Comment by f2404** [comment]
But, the package (```vid.stab``` in my case) is still shown as explicitly installed, not as a dependency...
